import React, { createContext, ReactNode, useContext, useState } from 'react';

type TranslationKeys = {
    // Tab titles
    home: string;
    categories: string;
    cart: string;
    wishlist: string;
    profile: string;
    // Common
    searchHere: string;
    viewAll: string;
    addToCart: string;
    buyNow: string;
    remove: string;
    cancel: string;
    save: string;
    apply: string;
    logout: string;
    // Home
    trending: string;
    bestSelling: string;
    newArrivals: string;
    seeAll: string;
    // Categories
    allCategories: string;
    // Cart
    emptyCart: string;
    emptyCartMsg: string;
    startShopping: string;
    orderSummary: string;
    subtotal: string;
    shippingFee: string;
    total: string;
    checkout: string;
    // Favorites
    emptyWishlist: string;
    emptyWishlistMsg: string;
    browseProducts: string;
    // Profile
    orders: string;
    payment: string;
    savedAddress: string;
    language: string;
    notification: string;
    settings: string;
    termsConditions: string;
    help: string;
    // Profile descriptions
    ordersDesc: string;
    wishlistDesc: string;
    paymentDesc: string;
    savedAddressDesc: string;
    languageDesc: string;
    notificationDesc: string;
    settingsDesc: string;
    termsDesc: string;
    helpDesc: string;
    // Orders
    orderHistory: string;
    ongoing: string;
    delivered: string;
    dispatched: string;
    viewDetails: string;
    // Payment
    paymentOptions: string;
    yourCard: string;
    wallet: string;
    addNewCard: string;
    cardNumber: string;
    cardHolderName: string;
    cvv: string;
    expDate: string;
    addCard: string;
    cashOnDelivery: string;
    // Address
    editAddress: string;
    address: string;
    phoneNumber: string;
    // Settings
    darkLight: string;
    // Language
    languages: string;
    // Help
    helpCenter: string;
    contactSupport: string;
    whatIssues: string;
    // Extra - Home
    hello: string;
    viewMore: string;
    megaSale: string;
    offerZone: string;
    furnitureDecor: string;
    comfortsModern: string;
    // Extra - Cart & Favorites
    qty: string;
    totalPrice: string;
    // Extra - Categories
    totalItems: string;
    // Extra - Profile modals
    editProfile: string;
    label: string;
    phoneNo: string;
    enterCardNumber: string;
    enterHolderName: string;
    enterCvv: string;
    enterPhone: string;
    enterAddress: string;
    rtl: string;
};

const translations: Record<string, TranslationKeys> = {
    English: {
        home: 'Home',
        categories: 'Categories',
        cart: 'Cart',
        wishlist: 'Wishlist',
        profile: 'Profile',
        searchHere: 'Search here...',
        viewAll: 'View All',
        addToCart: 'Add to Cart',
        buyNow: 'Buy Now',
        remove: 'Remove',
        cancel: 'Cancel',
        save: 'Save',
        apply: 'apply',
        logout: 'Logout',
        trending: 'Trending',
        bestSelling: 'Best Selling',
        newArrivals: 'New Arrivals',
        seeAll: 'See All',
        allCategories: 'All Categories',
        emptyCart: 'Your cart is empty',
        emptyCartMsg: 'Looks like you haven\'t added anything to your cart yet',
        startShopping: 'Start Shopping',
        orderSummary: 'Order Summary',
        subtotal: 'Subtotal',
        shippingFee: 'Shipping Fee',
        total: 'Total',
        checkout: 'Checkout',
        emptyWishlist: 'Your wishlist is empty',
        emptyWishlistMsg: 'Start adding items you love to your wishlist',
        browseProducts: 'Browse Products',
        orders: 'Orders',
        payment: 'Payment',
        savedAddress: 'Saved Address',
        language: 'Language',
        notification: 'Notification',
        settings: 'Settings',
        termsConditions: 'Terms & Conditions',
        help: 'Help',
        ordersDesc: 'Ongoing orders, Recent orders..',
        wishlistDesc: 'Your save product',
        paymentDesc: 'Saved card, Wallets',
        savedAddressDesc: 'Home, Office',
        languageDesc: 'Select your language here',
        notificationDesc: 'Offers, Order tracking messages',
        settingsDesc: 'app settings, Dark mode',
        termsDesc: 'T&C for use of platform',
        helpDesc: 'Customer Support, FAQs',
        orderHistory: 'Order History',
        ongoing: 'Ongoing',
        delivered: 'Delivered',
        dispatched: 'Dispatched',
        viewDetails: 'View Details',
        paymentOptions: 'Payment Options',
        yourCard: 'Your Card',
        wallet: 'Wallet',
        addNewCard: '+Add New Card',
        cardNumber: 'Card Number',
        cardHolderName: 'Card Holder Name',
        cvv: 'CVV',
        expDate: 'Exp. Date',
        addCard: 'Add Card',
        cashOnDelivery: 'Cash on Delivery',
        editAddress: 'Edit Address',
        address: 'Address',
        phoneNumber: 'Phone Number',
        darkLight: 'Dark/Light',
        languages: 'Languages',
        helpCenter: 'Help Center',
        contactSupport: 'Contact Support',
        whatIssues: 'What issues are you facing?',
        hello: 'Hello',
        viewMore: 'View More',
        megaSale: 'MEGA SALE\n50% OFF',
        offerZone: 'Offer Zone',
        furnitureDecor: 'Furniture And Decor',
        comfortsModern: 'Comforts & Modern\nLife Stylish Sofa',
        qty: 'Qty',
        totalPrice: 'Total price',
        totalItems: 'items available',
        editProfile: 'Edit Profile',
        label: 'Label',
        phoneNo: 'Phone no.',
        enterCardNumber: 'Enter card number',
        enterHolderName: 'Enter card holder name',
        enterCvv: 'Enter cvv',
        enterPhone: 'Enter phone number',
        enterAddress: 'Enter full address',
        rtl: 'RTL',
    },
    'Tiếng Việt': {
        home: 'Trang chủ',
        categories: 'Danh mục',
        cart: 'Giỏ hàng',
        wishlist: 'Yêu thích',
        profile: 'Cá nhân',
        searchHere: 'Tìm kiếm...',
        viewAll: 'Xem tất cả',
        addToCart: 'Thêm vào giỏ',
        buyNow: 'Mua ngay',
        remove: 'Xóa',
        cancel: 'Hủy',
        save: 'Lưu',
        apply: 'Áp dụng',
        logout: 'Đăng xuất',
        trending: 'Xu hướng',
        bestSelling: 'Bán chạy',
        newArrivals: 'Hàng mới',
        seeAll: 'Xem tất cả',
        allCategories: 'Tất cả danh mục',
        emptyCart: 'Giỏ hàng trống',
        emptyCartMsg: 'Bạn chưa thêm sản phẩm nào vào giỏ hàng',
        startShopping: 'Mua sắm ngay',
        orderSummary: 'Tóm tắt đơn hàng',
        subtotal: 'Tạm tính',
        shippingFee: 'Phí vận chuyển',
        total: 'Tổng cộng',
        checkout: 'Thanh toán',
        emptyWishlist: 'Danh sách yêu thích trống',
        emptyWishlistMsg: 'Hãy thêm sản phẩm bạn yêu thích',
        browseProducts: 'Xem sản phẩm',
        orders: 'Đơn hàng',
        payment: 'Thanh toán',
        savedAddress: 'Địa chỉ đã lưu',
        language: 'Ngôn ngữ',
        notification: 'Thông báo',
        settings: 'Cài đặt',
        termsConditions: 'Điều khoản & Điều kiện',
        help: 'Trợ giúp',
        ordersDesc: 'Đơn hàng đang xử lý, Đơn hàng gần đây..',
        wishlistDesc: 'Sản phẩm đã lưu',
        paymentDesc: 'Thẻ đã lưu, Ví điện tử',
        savedAddressDesc: 'Nhà, Văn phòng',
        languageDesc: 'Chọn ngôn ngữ của bạn',
        notificationDesc: 'Ưu đãi, Theo dõi đơn hàng',
        settingsDesc: 'Cài đặt ứng dụng, Chế độ tối',
        termsDesc: 'Điều khoản sử dụng',
        helpDesc: 'Hỗ trợ khách hàng, Câu hỏi thường gặp',
        orderHistory: 'Lịch sử đơn hàng',
        ongoing: 'Đang xử lý',
        delivered: 'Đã giao',
        dispatched: 'Đã gửi',
        viewDetails: 'Xem chi tiết',
        paymentOptions: 'Phương thức thanh toán',
        yourCard: 'Thẻ của bạn',
        wallet: 'Ví điện tử',
        addNewCard: '+Thêm thẻ mới',
        cardNumber: 'Số thẻ',
        cardHolderName: 'Tên chủ thẻ',
        cvv: 'CVV',
        expDate: 'Ngày hết hạn',
        addCard: 'Thêm thẻ',
        cashOnDelivery: 'Thanh toán khi nhận hàng',
        editAddress: 'Sửa địa chỉ',
        address: 'Địa chỉ',
        phoneNumber: 'Số điện thoại',
        darkLight: 'Tối/Sáng',
        languages: 'Ngôn ngữ',
        helpCenter: 'Trung tâm trợ giúp',
        contactSupport: 'Liên hệ hỗ trợ',
        whatIssues: 'Bạn đang gặp vấn đề gì?',
        hello: 'Xin chào',
        viewMore: 'Xem thêm',
        megaSale: 'GIẢM GIÁ\n50%',
        offerZone: 'Ưu đãi',
        furnitureDecor: 'Nội thất & Trang trí',
        comfortsModern: 'Sofa hiện đại\nPhong cách sống',
        qty: 'SL',
        totalPrice: 'Tổng tiền',
        totalItems: 'sản phẩm',
        editProfile: 'Sửa hồ sơ',
        label: 'Nhãn',
        phoneNo: 'SĐT',
        enterCardNumber: 'Nhập số thẻ',
        enterHolderName: 'Nhập tên chủ thẻ',
        enterCvv: 'Nhập CVV',
        enterPhone: 'Nhập số điện thoại',
        enterAddress: 'Nhập địa chỉ đầy đủ',
        rtl: 'RTL',
    },
    Spanish: {
        home: 'Inicio',
        categories: 'Categorías',
        cart: 'Carrito',
        wishlist: 'Favoritos',
        profile: 'Perfil',
        searchHere: 'Buscar aquí...',
        viewAll: 'Ver todo',
        addToCart: 'Añadir al carrito',
        buyNow: 'Comprar ahora',
        remove: 'Eliminar',
        cancel: 'Cancelar',
        save: 'Guardar',
        apply: 'Aplicar',
        logout: 'Cerrar sesión',
        trending: 'Tendencia',
        bestSelling: 'Más vendido',
        newArrivals: 'Novedades',
        seeAll: 'Ver todo',
        allCategories: 'Todas las categorías',
        emptyCart: 'Tu carrito está vacío',
        emptyCartMsg: 'Parece que aún no has añadido nada',
        startShopping: 'Empezar a comprar',
        orderSummary: 'Resumen del pedido',
        subtotal: 'Subtotal',
        shippingFee: 'Envío',
        total: 'Total',
        checkout: 'Pagar',
        emptyWishlist: 'Tu lista de deseos está vacía',
        emptyWishlistMsg: 'Empieza a añadir artículos que te gusten',
        browseProducts: 'Ver productos',
        orders: 'Pedidos',
        payment: 'Pago',
        savedAddress: 'Dirección guardada',
        language: 'Idioma',
        notification: 'Notificación',
        settings: 'Ajustes',
        termsConditions: 'Términos y condiciones',
        help: 'Ayuda',
        ordersDesc: 'Pedidos en curso, Pedidos recientes..',
        wishlistDesc: 'Tus productos guardados',
        paymentDesc: 'Tarjetas guardadas, Billeteras',
        savedAddressDesc: 'Casa, Oficina',
        languageDesc: 'Selecciona tu idioma',
        notificationDesc: 'Ofertas, Seguimiento de pedidos',
        settingsDesc: 'Ajustes de la app, Modo oscuro',
        termsDesc: 'T&C de uso de la plataforma',
        helpDesc: 'Soporte al cliente, Preguntas frecuentes',
        orderHistory: 'Historial de pedidos',
        ongoing: 'En curso',
        delivered: 'Entregado',
        dispatched: 'Enviado',
        viewDetails: 'Ver detalles',
        paymentOptions: 'Opciones de pago',
        yourCard: 'Tu tarjeta',
        wallet: 'Billetera',
        addNewCard: '+Añadir tarjeta',
        cardNumber: 'Número de tarjeta',
        cardHolderName: 'Nombre del titular',
        cvv: 'CVV',
        expDate: 'Fecha exp.',
        addCard: 'Añadir tarjeta',
        cashOnDelivery: 'Contra reembolso',
        editAddress: 'Editar dirección',
        address: 'Dirección',
        phoneNumber: 'Teléfono',
        darkLight: 'Oscuro/Claro',
        languages: 'Idiomas',
        helpCenter: 'Centro de ayuda',
        contactSupport: 'Contactar soporte',
        whatIssues: '¿Qué problemas tienes?',
        hello: 'Hola',
        viewMore: 'Ver más',
        megaSale: 'MEGA VENTA\n50% DCTO',
        offerZone: 'Zona de ofertas',
        furnitureDecor: 'Muebles y Decoración',
        comfortsModern: 'Sofá moderno\nEstilo de vida',
        qty: 'Cant',
        totalPrice: 'Precio total',
        totalItems: 'artículos disponibles',
        editProfile: 'Editar perfil',
        label: 'Etiqueta',
        phoneNo: 'Tel.',
        enterCardNumber: 'Ingrese número de tarjeta',
        enterHolderName: 'Ingrese nombre del titular',
        enterCvv: 'Ingrese CVV',
        enterPhone: 'Ingrese teléfono',
        enterAddress: 'Ingrese dirección completa',
        rtl: 'RTL',
    },
    France: {
        home: 'Accueil',
        categories: 'Catégories',
        cart: 'Panier',
        wishlist: 'Favoris',
        profile: 'Profil',
        searchHere: 'Rechercher ici...',
        viewAll: 'Voir tout',
        addToCart: 'Ajouter au panier',
        buyNow: 'Acheter',
        remove: 'Supprimer',
        cancel: 'Annuler',
        save: 'Sauvegarder',
        apply: 'Appliquer',
        logout: 'Déconnexion',
        trending: 'Tendance',
        bestSelling: 'Meilleures ventes',
        newArrivals: 'Nouveautés',
        seeAll: 'Voir tout',
        allCategories: 'Toutes les catégories',
        emptyCart: 'Votre panier est vide',
        emptyCartMsg: 'Vous n\'avez encore rien ajouté',
        startShopping: 'Commencer les achats',
        orderSummary: 'Résumé de la commande',
        subtotal: 'Sous-total',
        shippingFee: 'Frais de livraison',
        total: 'Total',
        checkout: 'Payer',
        emptyWishlist: 'Votre liste de souhaits est vide',
        emptyWishlistMsg: 'Ajoutez des articles que vous aimez',
        browseProducts: 'Parcourir les produits',
        orders: 'Commandes',
        payment: 'Paiement',
        savedAddress: 'Adresse enregistrée',
        language: 'Langue',
        notification: 'Notification',
        settings: 'Paramètres',
        termsConditions: 'Conditions générales',
        help: 'Aide',
        ordersDesc: 'Commandes en cours, Récentes..',
        wishlistDesc: 'Vos produits sauvegardés',
        paymentDesc: 'Cartes sauvegardées, Portefeuilles',
        savedAddressDesc: 'Maison, Bureau',
        languageDesc: 'Sélectionnez votre langue',
        notificationDesc: 'Offres, Suivi de commandes',
        settingsDesc: 'Paramètres, Mode sombre',
        termsDesc: 'CGU de la plateforme',
        helpDesc: 'Support client, FAQ',
        orderHistory: 'Historique des commandes',
        ongoing: 'En cours',
        delivered: 'Livré',
        dispatched: 'Expédié',
        viewDetails: 'Voir les détails',
        paymentOptions: 'Options de paiement',
        yourCard: 'Votre carte',
        wallet: 'Portefeuille',
        addNewCard: '+Ajouter une carte',
        cardNumber: 'Numéro de carte',
        cardHolderName: 'Nom du titulaire',
        cvv: 'CVV',
        expDate: 'Date exp.',
        addCard: 'Ajouter la carte',
        cashOnDelivery: 'Paiement à la livraison',
        editAddress: 'Modifier l\'adresse',
        address: 'Adresse',
        phoneNumber: 'Téléphone',
        darkLight: 'Sombre/Clair',
        languages: 'Langues',
        helpCenter: 'Centre d\'aide',
        contactSupport: 'Contacter le support',
        whatIssues: 'Quels problèmes rencontrez-vous?',
        hello: 'Bonjour',
        viewMore: 'Voir plus',
        megaSale: 'MÉGA PROMO\n50% DE REMISE',
        offerZone: 'Zone promo',
        furnitureDecor: 'Meubles et Déco',
        comfortsModern: 'Canapé moderne\nStyle de vie',
        qty: 'Qté',
        totalPrice: 'Prix total',
        totalItems: 'articles disponibles',
        editProfile: 'Modifier le profil',
        label: 'Étiquette',
        phoneNo: 'Tél.',
        enterCardNumber: 'Entrez le numéro de carte',
        enterHolderName: 'Entrez le nom du titulaire',
        enterCvv: 'Entrez le CVV',
        enterPhone: 'Entrez le téléphone',
        enterAddress: 'Entrez l\'adresse complète',
        rtl: 'RTL',
    },
    Portuguese: {
        home: 'Início',
        categories: 'Categorias',
        cart: 'Carrinho',
        wishlist: 'Favoritos',
        profile: 'Perfil',
        searchHere: 'Pesquisar aqui...',
        viewAll: 'Ver tudo',
        addToCart: 'Adicionar ao carrinho',
        buyNow: 'Comprar agora',
        remove: 'Remover',
        cancel: 'Cancelar',
        save: 'Salvar',
        apply: 'Aplicar',
        logout: 'Sair',
        trending: 'Tendência',
        bestSelling: 'Mais vendidos',
        newArrivals: 'Novidades',
        seeAll: 'Ver tudo',
        allCategories: 'Todas as categorias',
        emptyCart: 'Seu carrinho está vazio',
        emptyCartMsg: 'Parece que você ainda não adicionou nada',
        startShopping: 'Começar a comprar',
        orderSummary: 'Resumo do pedido',
        subtotal: 'Subtotal',
        shippingFee: 'Frete',
        total: 'Total',
        checkout: 'Finalizar',
        emptyWishlist: 'Sua lista de desejos está vazia',
        emptyWishlistMsg: 'Adicione itens que você gosta',
        browseProducts: 'Ver produtos',
        orders: 'Pedidos',
        payment: 'Pagamento',
        savedAddress: 'Endereço salvo',
        language: 'Idioma',
        notification: 'Notificação',
        settings: 'Configurações',
        termsConditions: 'Termos e Condições',
        help: 'Ajuda',
        ordersDesc: 'Pedidos em andamento, Recentes..',
        wishlistDesc: 'Seus produtos salvos',
        paymentDesc: 'Cartões salvos, Carteiras',
        savedAddressDesc: 'Casa, Escritório',
        languageDesc: 'Selecione seu idioma',
        notificationDesc: 'Ofertas, Rastreamento de pedidos',
        settingsDesc: 'Configurações do app, Modo escuro',
        termsDesc: 'T&C de uso da plataforma',
        helpDesc: 'Suporte ao cliente, Perguntas frequentes',
        orderHistory: 'Histórico de pedidos',
        ongoing: 'Em andamento',
        delivered: 'Entregue',
        dispatched: 'Enviado',
        viewDetails: 'Ver detalhes',
        paymentOptions: 'Opções de pagamento',
        yourCard: 'Seu cartão',
        wallet: 'Carteira',
        addNewCard: '+Adicionar cartão',
        cardNumber: 'Número do cartão',
        cardHolderName: 'Nome do titular',
        cvv: 'CVV',
        expDate: 'Data exp.',
        addCard: 'Adicionar cartão',
        cashOnDelivery: 'Pagamento na entrega',
        editAddress: 'Editar endereço',
        address: 'Endereço',
        phoneNumber: 'Telefone',
        darkLight: 'Escuro/Claro',
        languages: 'Idiomas',
        helpCenter: 'Central de ajuda',
        contactSupport: 'Contatar suporte',
        whatIssues: 'Quais problemas você está enfrentando?',
        hello: 'Olá',
        viewMore: 'Ver mais',
        megaSale: 'MEGA OFERTA\n50% DESC',
        offerZone: 'Zona de ofertas',
        furnitureDecor: 'Móveis e Decoração',
        comfortsModern: 'Sofá moderno\nEstilo de vida',
        qty: 'Qtd',
        totalPrice: 'Preço total',
        totalItems: 'itens disponíveis',
        editProfile: 'Editar perfil',
        label: 'Rótulo',
        phoneNo: 'Tel.',
        enterCardNumber: 'Digite o número do cartão',
        enterHolderName: 'Digite o nome do titular',
        enterCvv: 'Digite o CVV',
        enterPhone: 'Digite o telefone',
        enterAddress: 'Digite o endereço completo',
        rtl: 'RTL',
    },
    Russian: {
        home: 'Главная',
        categories: 'Категории',
        cart: 'Корзина',
        wishlist: 'Избранное',
        profile: 'Профиль',
        searchHere: 'Поиск...',
        viewAll: 'Показать все',
        addToCart: 'В корзину',
        buyNow: 'Купить',
        remove: 'Удалить',
        cancel: 'Отмена',
        save: 'Сохранить',
        apply: 'Применить',
        logout: 'Выйти',
        trending: 'В тренде',
        bestSelling: 'Бестселлеры',
        newArrivals: 'Новинки',
        seeAll: 'Все',
        allCategories: 'Все категории',
        emptyCart: 'Корзина пуста',
        emptyCartMsg: 'Вы ещё ничего не добавили в корзину',
        startShopping: 'Начать покупки',
        orderSummary: 'Итого по заказу',
        subtotal: 'Подитог',
        shippingFee: 'Доставка',
        total: 'Итого',
        checkout: 'Оформить',
        emptyWishlist: 'Список желаний пуст',
        emptyWishlistMsg: 'Добавьте понравившиеся товары',
        browseProducts: 'Смотреть товары',
        orders: 'Заказы',
        payment: 'Оплата',
        savedAddress: 'Сохранённый адрес',
        language: 'Язык',
        notification: 'Уведомления',
        settings: 'Настройки',
        termsConditions: 'Условия использования',
        help: 'Помощь',
        ordersDesc: 'Текущие заказы, Недавние заказы..',
        wishlistDesc: 'Сохранённые товары',
        paymentDesc: 'Сохранённые карты, Кошельки',
        savedAddressDesc: 'Дом, Офис',
        languageDesc: 'Выберите ваш язык',
        notificationDesc: 'Акции, Отслеживание заказов',
        settingsDesc: 'Настройки приложения, Тёмный режим',
        termsDesc: 'Условия использования платформы',
        helpDesc: 'Поддержка клиентов, Частые вопросы',
        orderHistory: 'История заказов',
        ongoing: 'В процессе',
        delivered: 'Доставлен',
        dispatched: 'Отправлен',
        viewDetails: 'Подробнее',
        paymentOptions: 'Способы оплаты',
        yourCard: 'Ваша карта',
        wallet: 'Кошелёк',
        addNewCard: '+Добавить карту',
        cardNumber: 'Номер карты',
        cardHolderName: 'Имя владельца',
        cvv: 'CVV',
        expDate: 'Срок действия',
        addCard: 'Добавить карту',
        cashOnDelivery: 'Оплата при доставке',
        editAddress: 'Редактировать адрес',
        address: 'Адрес',
        phoneNumber: 'Телефон',
        darkLight: 'Тёмная/Светлая',
        languages: 'Языки',
        helpCenter: 'Центр помощи',
        contactSupport: 'Связаться с поддержкой',
        whatIssues: 'С какой проблемой вы столкнулись?',
        hello: 'Привет',
        viewMore: 'Подробнее',
        megaSale: 'МЕГА СКИДКА\n50%',
        offerZone: 'Зона скидок',
        furnitureDecor: 'Мебель и Декор',
        comfortsModern: 'Современный диван\nСтильная жизнь',
        qty: 'Кол',
        totalPrice: 'Итого',
        totalItems: 'товаров',
        editProfile: 'Редактировать профиль',
        label: 'Метка',
        phoneNo: 'Тел.',
        enterCardNumber: 'Введите номер карты',
        enterHolderName: 'Введите имя владельца',
        enterCvv: 'Введите CVV',
        enterPhone: 'Введите телефон',
        enterAddress: 'Введите полный адрес',
        rtl: 'RTL',
    },
    Chinese: {
        home: '首页',
        categories: '分类',
        cart: '购物车',
        wishlist: '收藏',
        profile: '个人',
        searchHere: '搜索...',
        viewAll: '查看全部',
        addToCart: '加入购物车',
        buyNow: '立即购买',
        remove: '删除',
        cancel: '取消',
        save: '保存',
        apply: '应用',
        logout: '退出登录',
        trending: '热门',
        bestSelling: '畅销',
        newArrivals: '新品',
        seeAll: '查看全部',
        allCategories: '所有分类',
        emptyCart: '购物车为空',
        emptyCartMsg: '您还没有添加任何商品',
        startShopping: '开始购物',
        orderSummary: '订单摘要',
        subtotal: '小计',
        shippingFee: '运费',
        total: '总计',
        checkout: '结算',
        emptyWishlist: '收藏夹为空',
        emptyWishlistMsg: '添加您喜欢的商品',
        browseProducts: '浏览商品',
        orders: '订单',
        payment: '支付',
        savedAddress: '已保存地址',
        language: '语言',
        notification: '通知',
        settings: '设置',
        termsConditions: '条款与条件',
        help: '帮助',
        ordersDesc: '进行中的订单，最近的订单..',
        wishlistDesc: '已保存的商品',
        paymentDesc: '已保存的卡片，钱包',
        savedAddressDesc: '家，办公室',
        languageDesc: '选择您的语言',
        notificationDesc: '优惠，订单跟踪',
        settingsDesc: '应用设置，深色模式',
        termsDesc: '平台使用条款',
        helpDesc: '客户支持，常见问题',
        orderHistory: '订单历史',
        ongoing: '进行中',
        delivered: '已送达',
        dispatched: '已发货',
        viewDetails: '查看详情',
        paymentOptions: '支付方式',
        yourCard: '您的卡片',
        wallet: '钱包',
        addNewCard: '+添加新卡',
        cardNumber: '卡号',
        cardHolderName: '持卡人姓名',
        cvv: 'CVV',
        expDate: '有效期',
        addCard: '添加卡片',
        cashOnDelivery: '货到付款',
        editAddress: '编辑地址',
        address: '地址',
        phoneNumber: '电话',
        darkLight: '深色/浅色',
        languages: '语言',
        helpCenter: '帮助中心',
        contactSupport: '联系客服',
        whatIssues: '您遇到了什么问题？',
        hello: '你好',
        viewMore: '查看更多',
        megaSale: '大促销\n五折优惠',
        offerZone: '优惠专区',
        furnitureDecor: '家具与装饰',
        comfortsModern: '现代舒适\n时尚沙发',
        qty: '数量',
        totalPrice: '总价',
        totalItems: '件商品',
        editProfile: '编辑资料',
        label: '标签',
        phoneNo: '电话',
        enterCardNumber: '输入卡号',
        enterHolderName: '输入持卡人姓名',
        enterCvv: '输入CVV',
        enterPhone: '输入电话号码',
        enterAddress: '输入完整地址',
        rtl: 'RTL',
    },
};

interface LanguageContextType {
    language: string;
    setLanguage: (lang: string) => void;
    t: TranslationKeys;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

interface LanguageProviderProps {
    children: ReactNode;
}

export function LanguageProvider({ children }: LanguageProviderProps) {
    const [language, setLanguage] = useState('English');

    const t = translations[language] || translations['English'];

    return (
        <LanguageContext.Provider value={{ language, setLanguage, t }}>
            {children}
        </LanguageContext.Provider>
    );
}

export function useLanguage() {
    const context = useContext(LanguageContext);
    if (context === undefined) {
        throw new Error('useLanguage must be used within a LanguageProvider');
    }
    return context;
}
